library(data.table)
library(tidyverse)

#### SET STATE LIST
state_list <- c("FL","PA","CA","TX","OH","MD")

#LOAD IN: Produced on cluster: rawcharge shrunk to shoppable list of cpts
raw_shoppable <- as.data.frame(fread("Data/rawcharge_shoppable_cpt.csv") )
shoppable_list <- as.data.frame(fread("Data/shoppable_services.csv", data.table = F) )

# Load Raw Turquoise Data
provider <- as.data.frame(fread("/Users/daniel/Turquoise/working/price_transparency_provider.csv"))
healthsystem <- as.data.frame(fread("/Users/daniel/Turquoise/working/price_transparency_healthsystem.csv") )
plan <- as.data.frame(fread("/Users/daniel/Turquoise/working/price_transparency_plan.csv") )
payerclass <- as.data.frame(fread("/Users/daniel/Turquoise/working/price_transparency_payerclass.csv") )


######################################################################
######################################################################
#### Produce raw_charge shoppable for focal states
focal_providers <- provider %>% filter(state %in% state_list)
raw <- raw_shoppable %>% filter(provider_id %in% focal_providers$id)
######## Hospital level characteristics
provider$hosp_name <- provider$name
prov <- provider %>% filter(state %in% state_list) %>% select(id, state, hosp_name, health_system_id, total_beds, total_employees, compliance_score, compliance_score_adjusted,acute_care_facility, hospital_type, hospital_ownership, starts_with("provides_"))
######## System level characteristics
sys <- healthsystem %>% filter(id %in% focal_providers$health_system_id)
######################################################################
######################################################################


# Join separate data frames (provider and systems with raw charge data (shoppable services))
prov.sys <- left_join(x = prov, y = sys, by=c("health_system_id" = "id") )
df <- left_join(x = raw, y = prov.sys, by=c("provider_id" = "id"))

### Join with Plan and Payerclass 
plan <- plan %>% select(id,name,payer_id, payer_class_id)
payerclass <- payerclass %>% select(id, name)
health_plan <- left_join(x = plan, y = payerclass, by=c("payer_class_id"="id"))
df <- left_join(x = df, y = health_plan, by=c("plan_id" = "id"))
head(df)

##########
######CLEANING OF DATA
##########
## Step 1: filter by relevant payer classes
df <- df %>% filter(name.y %in% c("Commercial", "Dual", "List Price", "Medicaid", "Medicare", 
                                  "Medicare Reference Pricing (Generated by Turquoise Health", "Self-Pay"))
## Step 2: outliers as identified by Turquoise
df <- df %>% filter(rate_is_outlier=="f")

## Step 3: Wrong Rate Removal CPT equals Rate
df$wrong.rate <- ifelse(df$cpt == df$rate, 1, 0)
df <- df %>% filter(wrong.rate==0)
###########

df <- df %>% distinct(provider_id, cpt, rate, plan_id, .keep_all = TRUE)


#################################
##### VARIABLE SELECTION ########
#################################
df <- df %>% select(cpt, rev_code, rate, rate_is_outlier, provider_id, plan_id, 
                    rate_currency, service_area, turquoise_derived_rate, id, 
                    total_beds, total_employees, compliance_score, compliance_score_adjusted, 
                    state, acute_care_facility, hospital_type, hospital_ownership, hosp_name, 
                    health_system_id, health_sys_id,health_sys_name, health_sys_city, 
                    health_sys_state, total_mds, maj_inv_owned, sys_teachint, sys_multistate,
                    sys_beds, sys_res, name.x, name.y)
#################################
#################################


#### Price: Need to calculate table for state.adj, list, medicare, commercial and then match back by provider (one line per provider): tbd

### hospital line price info for duplicates

hist(df$rate[df$name.y=="Commercial"], xlim = c(0,4000), breaks = 1000, xlab = "Raw rate in USD", main = "Raw rates self-pay" )
hist(df$rate[df$name.y=="Self-Pay"], xlim = c(0,4000), breaks = 1000, xlab = "Raw rate in USD", main = "Raw rates self-pay")
hist(df$rate[df$name.y=="Medicare"], xlim = c(0,1500), breaks = 1000, xlab = "Raw rate in USD", main = "Raw rates Medicare")


#### Hospital rate by CPT and Plan ID WHICH SHOULD HAVE ONLY ONE LINE BUT HERE WE DEAL WITH DATA ENTRY ERRORS (BUIDLING MEDIAN)
df.x <- df %>% group_by(provider_id, cpt, plan_id) %>% mutate(h_rate_count = n(),h_rate_mean = mean(rate), h_rate_median = median(rate), h_rate_min = min(rate), h_rate_max = max(rate), h_rate_sd = sd(rate))
df.x <- as.data.frame(df.x)
df.x$h_rate_sd <- ifelse( is.na(df.x$h_rate_sd) , 0, df.x$h_rate_sd)

## Bring down to one line per case as should be normally the case.
df.y <- df.x %>% distinct(provider_id, plan_id, cpt, .keep_all = TRUE)   # single lines per case
df.y <- as.data.frame(df.y) 

hist(df.y$h_rate_median[df.x$name.y=="Commercial"], xlim = c(0,4000), breaks = 1000)
hist(df.y$h_rate_median[df.x$name.y=="Self-Pay"], xlim = c(0,4000), breaks = 1000)
hist(df.y$h_rate_median[df.x$name.y=="Medicare"], xlim = c(0,1500), breaks = 1000)

hist(df.y$h_rate_mean[df.x$name.y=="Commercial"], xlim = c(0,4000), breaks = 1000)
hist(df.y$h_rate_mean[df.x$name.y=="Self-Pay"], xlim = c(0,4000), breaks = 1000)
hist(df.y$h_rate_mean[df.x$name.y=="Medicare"], xlim = c(0,1500), breaks = 1000)


###
### Generate h_ins_* variables: stands for hospital_insurance_* and really refers to PAYER (e.g., insurance, self-pay etc.)

df.z <- df.y %>% group_by(provider_id, cpt, name.y) %>% mutate(h_ins_count = n(),h_ins_mean = mean(h_rate_median), h_ins_median = median(h_rate_median), h_ins_iqr = IQR(h_rate_median), h_ins_min = min(h_rate_median), h_ins_max = max(h_rate_median), h_ins_sd = sd(h_rate_median))
df.z <- as.data.frame(df.z)

### Remove duplicate lines after processing new variables:
df.z <- df.z %>% distinct(provider_id, cpt, name.y, .keep_all = TRUE)
df.z <- as.data.frame(df.z)


df.z$h_ins_sd <- ifelse(is.na(df.z$h_ins_sd), 0, df.z$h_ins_sd)
fwrite(df.z, file = "Data/data_clean_mutated.csv")
